import type{ PersonalInfoForm } from "../types/types";

export const emptyPersonalInfo: Omit<PersonalInfoForm, "birth_date"> & { birth_date: string } = {
  first_name: "",
  last_name: "",
  national_code: "",
  birth_date: new Date().toISOString(),
  birth_province: "",
  birth_city: "",
  id_number: "",
  issue_city: "",
  issue_province: "",
  religion: "",
  marital_status: "",
  gender: "",
  father_name: "",
  father_job: "",
  father_education: "",
  mother_name: "",
  mother_job: "",
  mother_education: "",
  siblings_count: 0,
  children_count: 0,
  residence_province: "",
  residence_city: "",
  address: "",
  postal_code: "",
  phone: "",
  email: "",
  emergency_contact_name: "",
  emergency_contact_relation: "",
  emergency_contact_phone: "",
  avatar_url: "",
};
